# Generated by Django 5.2.7 on 2025-10-14 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image_url",
            field=models.URLField(default="Insert valid URL here"),
            preserve_default=False,
        ),
    ]
